### ISSUE TITLE
ctypes error

### ISSUE THREAD

**Issue by abdallah-hader** [baaziznasser/nbsapi#2]
Hi, I used this module in one of the projects, and it was a great library, unfortunately it won't work for some people, and they were getting the following error, of course a lot of people faced this problem.
  File "NBSapi\NBSapi.py", line 85, in GetVoices
_ctypes.COMError: (-2147200966, None, (None, None, None, 0, None))

**Comment by baaziznasser** [comment]
hello friend @abdallah-hader
am realy sorry for my late reply.
so, i searched about this problem, it happen when no voices found on the sapi 5, or if the sapi5 is not installed.
so i will add a new function to check if sapi is avalable or no, by this way we will be able to deal with this error.
i will share an update here on github soon with this function added.

**Comment by baaziznasser** [comment]
goodmorning dear  @abdallah-hader 
now the problem has solved, I've added an function to check if the sapi is avalable and contains voices or now:
```
import NBSapi
if NBSapi.is_sapi():
	print("yes the sapi5 is ready to use")
else:
	print("no the sapi5 is not ready yet")
```
where you can try the new changes by downloading the file
(NBSapi.py)[https://github.com/baaziznasser/nbsapi/blob/main/NBSapi/NBSapi.py]
and replace the currently installed one.
